server:
  port: 8080

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:h2:mem:transactiondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  cloud:
    function:
      definition: processTransaction;sendTransaction
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          configuration:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: com.plutus.kotak.commonlibs.serializer.BankTransactionAvroSerializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: com.plutus.kotak.commonlibs.serializer.BankTransactionAvroDeserializer
            auto.offset.reset: earliest
            enable.auto.commit: true
            group.id: transaction-group
            client.id: transaction-client
            retries: 3
            acks: all
      bindings:
        processTransaction-in-0:
          destination: transactions
          group: transaction-group
          contentType: application/*+avro
        sendTransaction-out-0:
          destination: transactions
          contentType: application/*+avro
      default-binder: kafka
      default-producer-properties:
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: com.plutus.kotak.commonlibs.serializer.BankTransactionAvroSerializer
      default-consumer-properties:
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: com.plutus.kotak.commonlibs.serializer.BankTransactionAvroDeserializer
        auto.offset.reset: earliest
        enable.auto.commit: true

logging:
  level:
    root: INFO
    com.plutus.kotak.commonlibs: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.cloud.stream: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 